package Pojos;
// Generated Oct 24, 2024 12:41:15 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Asignacion generated by hbm2java
 */
public class Asignacion  implements java.io.Serializable {


     private int codigoAsignacion;
     private Examen examen;
     private Usuario usuarioByUsuarioIngreso;
     private Usuario usuarioByUsuarioModifica;
     private Usuario usuarioByEvaluado;
     private Boolean estado;
     private Date fechaIngreso;
     private Date fechaModifica;

    public Asignacion() {
    }

	
    public Asignacion(int codigoAsignacion) {
        this.codigoAsignacion = codigoAsignacion;
    }
    public Asignacion(int codigoAsignacion, Examen examen, Usuario usuarioByUsuarioIngreso, Usuario usuarioByUsuarioModifica, Usuario usuarioByEvaluado, Boolean estado, Date fechaIngreso, Date fechaModifica) {
       this.codigoAsignacion = codigoAsignacion;
       this.examen = examen;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.usuarioByEvaluado = usuarioByEvaluado;
       this.estado = estado;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
    }
   
    public int getCodigoAsignacion() {
        return this.codigoAsignacion;
    }
    
    public void setCodigoAsignacion(int codigoAsignacion) {
        this.codigoAsignacion = codigoAsignacion;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Usuario getUsuarioByEvaluado() {
        return this.usuarioByEvaluado;
    }
    
    public void setUsuarioByEvaluado(Usuario usuarioByEvaluado) {
        this.usuarioByEvaluado = usuarioByEvaluado;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }




}


