package Pojos;
// Generated Oct 3, 2024 9:49:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Certificacion generated by hbm2java
 */
public class Certificacion  implements java.io.Serializable {


     private int numeroCertificacion;
     private Comando comando;
     private Examen examen;
     private MotivoEvaluacion motivoEvaluacion;
     private MotivoNoApto motivoNoApto;
     private Usuario usuarioByUsarioIngresa;
     private Usuario usuarioByUsuarioModifica;
     private boolean estado;
     private String resultadoFinal;
     private Date fechaIngreso;
     private Date fechaModifica;

    public Certificacion() {
    }

	
    public Certificacion(int numeroCertificacion, boolean estado) {
        this.numeroCertificacion = numeroCertificacion;
        this.estado = estado;
    }
    public Certificacion(int numeroCertificacion, Comando comando, Examen examen, MotivoEvaluacion motivoEvaluacion, MotivoNoApto motivoNoApto, Usuario usuarioByUsarioIngresa, Usuario usuarioByUsuarioModifica, boolean estado, String resultadoFinal, Date fechaIngreso, Date fechaModifica) {
       this.numeroCertificacion = numeroCertificacion;
       this.comando = comando;
       this.examen = examen;
       this.motivoEvaluacion = motivoEvaluacion;
       this.motivoNoApto = motivoNoApto;
       this.usuarioByUsarioIngresa = usuarioByUsarioIngresa;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.estado = estado;
       this.resultadoFinal = resultadoFinal;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
    }
   
    public int getNumeroCertificacion() {
        return this.numeroCertificacion;
    }
    
    public void setNumeroCertificacion(int numeroCertificacion) {
        this.numeroCertificacion = numeroCertificacion;
    }
    public Comando getComando() {
        return this.comando;
    }
    
    public void setComando(Comando comando) {
        this.comando = comando;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public MotivoEvaluacion getMotivoEvaluacion() {
        return this.motivoEvaluacion;
    }
    
    public void setMotivoEvaluacion(MotivoEvaluacion motivoEvaluacion) {
        this.motivoEvaluacion = motivoEvaluacion;
    }
    public MotivoNoApto getMotivoNoApto() {
        return this.motivoNoApto;
    }
    
    public void setMotivoNoApto(MotivoNoApto motivoNoApto) {
        this.motivoNoApto = motivoNoApto;
    }
    public Usuario getUsuarioByUsarioIngresa() {
        return this.usuarioByUsarioIngresa;
    }
    
    public void setUsuarioByUsarioIngresa(Usuario usuarioByUsarioIngresa) {
        this.usuarioByUsarioIngresa = usuarioByUsarioIngresa;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getResultadoFinal() {
        return this.resultadoFinal;
    }
    
    public void setResultadoFinal(String resultadoFinal) {
        this.resultadoFinal = resultadoFinal;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }




}


