package Pojos;
// Generated Oct 24, 2024 12:41:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comando generated by hbm2java
 */
public class Comando  implements java.io.Serializable {


     private Integer codigoComando;
     private Boolean estado;
     private String nombreComando;
     private Set usuarios = new HashSet(0);

    public Comando() {
    }

    public Comando(Boolean estado, String nombreComando, Set usuarios) {
       this.estado = estado;
       this.nombreComando = nombreComando;
       this.usuarios = usuarios;
    }
   
    public Integer getCodigoComando() {
        return this.codigoComando;
    }
    
    public void setCodigoComando(Integer codigoComando) {
        this.codigoComando = codigoComando;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombreComando() {
        return this.nombreComando;
    }
    
    public void setNombreComando(String nombreComando) {
        this.nombreComando = nombreComando;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


