package Pojos;
// Generated Oct 24, 2024 12:41:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DepartamentoResidencia generated by hbm2java
 */
public class DepartamentoResidencia  implements java.io.Serializable {


     private Integer codigoDepartamento;
     private Boolean estado;
     private String nombreDepartamento;
     private Set usuarios = new HashSet(0);

    public DepartamentoResidencia() {
    }

    public DepartamentoResidencia(Boolean estado, String nombreDepartamento, Set usuarios) {
       this.estado = estado;
       this.nombreDepartamento = nombreDepartamento;
       this.usuarios = usuarios;
    }
   
    public Integer getCodigoDepartamento() {
        return this.codigoDepartamento;
    }
    
    public void setCodigoDepartamento(Integer codigoDepartamento) {
        this.codigoDepartamento = codigoDepartamento;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


