package Pojos;
// Generated Sep 3, 2024 5:05:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DetalleExamen generated by hbm2java
 */
public class DetalleExamen  implements java.io.Serializable {


     private int codigoDetalle;
     private Examen examen;
     private Pregunta pregunta;
     private Usuario usuarioByUsuarioIngreso;
     private Usuario usuarioByUsuarioModifica;
     private Boolean estado;
     private String respuestaDada;
     private Date fechaIngreso;
     private Date fechaModifica;

    public DetalleExamen() {
    }

	
    public DetalleExamen(int codigoDetalle) {
        this.codigoDetalle = codigoDetalle;
    }
    public DetalleExamen(int codigoDetalle, Examen examen, Pregunta pregunta, Usuario usuarioByUsuarioIngreso, Usuario usuarioByUsuarioModifica, Boolean estado, String respuestaDada, Date fechaIngreso, Date fechaModifica) {
       this.codigoDetalle = codigoDetalle;
       this.examen = examen;
       this.pregunta = pregunta;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.estado = estado;
       this.respuestaDada = respuestaDada;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
    }
   
    public int getCodigoDetalle() {
        return this.codigoDetalle;
    }
    
    public void setCodigoDetalle(int codigoDetalle) {
        this.codigoDetalle = codigoDetalle;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getRespuestaDada() {
        return this.respuestaDada;
    }
    
    public void setRespuestaDada(String respuestaDada) {
        this.respuestaDada = respuestaDada;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }




}


