package Pojos;
// Generated Oct 24, 2024 12:41:15 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private int codigoDetalle;
     private Examen examen;
     private Pregunta pregunta;
     private Usuario usuarioByUsuarioIngreso;
     private Usuario usuarioByUsuarioModifica;
     private Boolean estado;
     private String serie;
     private String instruccion;
     private Date fechaIngreso;
     private Date fechaModifica;

    public Detalle() {
    }

	
    public Detalle(int codigoDetalle) {
        this.codigoDetalle = codigoDetalle;
    }
    public Detalle(int codigoDetalle, Examen examen, Pregunta pregunta, Usuario usuarioByUsuarioIngreso, Usuario usuarioByUsuarioModifica, Boolean estado, String serie, String instruccion, Date fechaIngreso, Date fechaModifica) {
       this.codigoDetalle = codigoDetalle;
       this.examen = examen;
       this.pregunta = pregunta;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.estado = estado;
       this.serie = serie;
       this.instruccion = instruccion;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
    }
   
    public int getCodigoDetalle() {
        return this.codigoDetalle;
    }
    
    public void setCodigoDetalle(int codigoDetalle) {
        this.codigoDetalle = codigoDetalle;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public String getInstruccion() {
        return this.instruccion;
    }
    
    public void setInstruccion(String instruccion) {
        this.instruccion = instruccion;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }




}


