package Pojos;
// Generated Oct 24, 2024 12:41:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Examen generated by hbm2java
 */
public class Examen  implements java.io.Serializable {


     private int codigoExamen;
     private Empleo empleo;
     private Motivo motivo;
     private Usuario usuarioByUsuarioIngreso;
     private Usuario usuarioByUsuarioModifica;
     private Boolean estado;
     private Date fechaEvaluacion;
     private Integer punteoMaximo;
     private Date fechaIngreso;
     private Date fechaModifica;
     private Set asignacions = new HashSet(0);
     private Set detalles = new HashSet(0);

    public Examen() {
    }

	
    public Examen(int codigoExamen) {
        this.codigoExamen = codigoExamen;
    }
    public Examen(int codigoExamen, Empleo empleo, Motivo motivo, Usuario usuarioByUsuarioIngreso, Usuario usuarioByUsuarioModifica, Boolean estado, Date fechaEvaluacion, Integer punteoMaximo, Date fechaIngreso, Date fechaModifica, Set asignacions, Set detalles) {
       this.codigoExamen = codigoExamen;
       this.empleo = empleo;
       this.motivo = motivo;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.estado = estado;
       this.fechaEvaluacion = fechaEvaluacion;
       this.punteoMaximo = punteoMaximo;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
       this.asignacions = asignacions;
       this.detalles = detalles;
    }
   
    public int getCodigoExamen() {
        return this.codigoExamen;
    }
    
    public void setCodigoExamen(int codigoExamen) {
        this.codigoExamen = codigoExamen;
    }
    public Empleo getEmpleo() {
        return this.empleo;
    }
    
    public void setEmpleo(Empleo empleo) {
        this.empleo = empleo;
    }
    public Motivo getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(Motivo motivo) {
        this.motivo = motivo;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFechaEvaluacion() {
        return this.fechaEvaluacion;
    }
    
    public void setFechaEvaluacion(Date fechaEvaluacion) {
        this.fechaEvaluacion = fechaEvaluacion;
    }
    public Integer getPunteoMaximo() {
        return this.punteoMaximo;
    }
    
    public void setPunteoMaximo(Integer punteoMaximo) {
        this.punteoMaximo = punteoMaximo;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }
    public Set getAsignacions() {
        return this.asignacions;
    }
    
    public void setAsignacions(Set asignacions) {
        this.asignacions = asignacions;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }




}


