package Pojos;
// Generated Sep 3, 2024 5:05:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Examen generated by hbm2java
 */
public class Examen  implements java.io.Serializable {


     private int codigoExamen;
     private Empleo empleo;
     private Persona persona;
     private Usuario usuarioByUsuarioIngreso;
     private Usuario usuarioByUsuarioModifica;
     private Boolean estado;
     private Date fechaEvaluacion;
     private Integer punteoTotal;
     private Date fechaIngreso;
     private Date fechaModifica;
     private Set certificacions = new HashSet(0);
     private Set detalleExamens = new HashSet(0);

    public Examen() {
    }

	
    public Examen(int codigoExamen) {
        this.codigoExamen = codigoExamen;
    }
    public Examen(int codigoExamen, Empleo empleo, Persona persona, Usuario usuarioByUsuarioIngreso, Usuario usuarioByUsuarioModifica, Boolean estado, Date fechaEvaluacion, Integer punteoTotal, Date fechaIngreso, Date fechaModifica, Set certificacions, Set detalleExamens) {
       this.codigoExamen = codigoExamen;
       this.empleo = empleo;
       this.persona = persona;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.estado = estado;
       this.fechaEvaluacion = fechaEvaluacion;
       this.punteoTotal = punteoTotal;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
       this.certificacions = certificacions;
       this.detalleExamens = detalleExamens;
    }
   
    public int getCodigoExamen() {
        return this.codigoExamen;
    }
    
    public void setCodigoExamen(int codigoExamen) {
        this.codigoExamen = codigoExamen;
    }
    public Empleo getEmpleo() {
        return this.empleo;
    }
    
    public void setEmpleo(Empleo empleo) {
        this.empleo = empleo;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFechaEvaluacion() {
        return this.fechaEvaluacion;
    }
    
    public void setFechaEvaluacion(Date fechaEvaluacion) {
        this.fechaEvaluacion = fechaEvaluacion;
    }
    public Integer getPunteoTotal() {
        return this.punteoTotal;
    }
    
    public void setPunteoTotal(Integer punteoTotal) {
        this.punteoTotal = punteoTotal;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }
    public Set getCertificacions() {
        return this.certificacions;
    }
    
    public void setCertificacions(Set certificacions) {
        this.certificacions = certificacions;
    }
    public Set getDetalleExamens() {
        return this.detalleExamens;
    }
    
    public void setDetalleExamens(Set detalleExamens) {
        this.detalleExamens = detalleExamens;
    }




}


