package Pojos;
// Generated Oct 3, 2024 9:49:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grado generated by hbm2java
 */
public class Grado  implements java.io.Serializable {


     private int codigoGrado;
     private Boolean estado;
     private String nombreGrado;
     private Set usuarios = new HashSet(0);

    public Grado() {
    }

	
    public Grado(int codigoGrado) {
        this.codigoGrado = codigoGrado;
    }
    public Grado(int codigoGrado, Boolean estado, String nombreGrado, Set usuarios) {
       this.codigoGrado = codigoGrado;
       this.estado = estado;
       this.nombreGrado = nombreGrado;
       this.usuarios = usuarios;
    }
   
    public int getCodigoGrado() {
        return this.codigoGrado;
    }
    
    public void setCodigoGrado(int codigoGrado) {
        this.codigoGrado = codigoGrado;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombreGrado() {
        return this.nombreGrado;
    }
    
    public void setNombreGrado(String nombreGrado) {
        this.nombreGrado = nombreGrado;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


