package Pojos;
// Generated Oct 3, 2024 9:49:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MotivoEvaluacion generated by hbm2java
 */
public class MotivoEvaluacion  implements java.io.Serializable {


     private int codigoMotivo;
     private Usuario usuarioByUsuarioModifica;
     private Usuario usuarioByUsuarioIngreso;
     private Boolean estado;
     private String nombreMotivo;
     private Date fechaIngreso;
     private Date fechaModifica;
     private Set certificacions = new HashSet(0);

    public MotivoEvaluacion() {
    }

	
    public MotivoEvaluacion(int codigoMotivo) {
        this.codigoMotivo = codigoMotivo;
    }
    public MotivoEvaluacion(int codigoMotivo, Usuario usuarioByUsuarioModifica, Usuario usuarioByUsuarioIngreso, Boolean estado, String nombreMotivo, Date fechaIngreso, Date fechaModifica, Set certificacions) {
       this.codigoMotivo = codigoMotivo;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.estado = estado;
       this.nombreMotivo = nombreMotivo;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
       this.certificacions = certificacions;
    }
   
    public int getCodigoMotivo() {
        return this.codigoMotivo;
    }
    
    public void setCodigoMotivo(int codigoMotivo) {
        this.codigoMotivo = codigoMotivo;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombreMotivo() {
        return this.nombreMotivo;
    }
    
    public void setNombreMotivo(String nombreMotivo) {
        this.nombreMotivo = nombreMotivo;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }
    public Set getCertificacions() {
        return this.certificacions;
    }
    
    public void setCertificacions(Set certificacions) {
        this.certificacions = certificacions;
    }




}


