package Pojos;
// Generated Oct 23, 2024 11:02:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Motivo generated by hbm2java
 */
public class Motivo  implements java.io.Serializable {


     private int codigoMotivo;
     private Boolean estado;
     private String nombreMotivo;
     private Set examens = new HashSet(0);

    public Motivo() {
    }

	
    public Motivo(int codigoMotivo) {
        this.codigoMotivo = codigoMotivo;
    }
    public Motivo(int codigoMotivo, Boolean estado, String nombreMotivo, Set examens) {
       this.codigoMotivo = codigoMotivo;
       this.estado = estado;
       this.nombreMotivo = nombreMotivo;
       this.examens = examens;
    }
   
    public int getCodigoMotivo() {
        return this.codigoMotivo;
    }
    
    public void setCodigoMotivo(int codigoMotivo) {
        this.codigoMotivo = codigoMotivo;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombreMotivo() {
        return this.nombreMotivo;
    }
    
    public void setNombreMotivo(String nombreMotivo) {
        this.nombreMotivo = nombreMotivo;
    }
    public Set getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set examens) {
        this.examens = examens;
    }




}


