package Pojos;
// Generated Sep 3, 2024 5:05:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MotivoNoApto generated by hbm2java
 */
public class MotivoNoApto  implements java.io.Serializable {


     private int codigoNoApto;
     private Usuario usuarioByUsuarioIngreso;
     private Usuario usuarioByUsuarioModifica;
     private Boolean estado;
     private String nombreMotivo;
     private Date fechaIngreso;
     private Date fechaModifica;
     private Set certificacions = new HashSet(0);

    public MotivoNoApto() {
    }

	
    public MotivoNoApto(int codigoNoApto) {
        this.codigoNoApto = codigoNoApto;
    }
    public MotivoNoApto(int codigoNoApto, Usuario usuarioByUsuarioIngreso, Usuario usuarioByUsuarioModifica, Boolean estado, String nombreMotivo, Date fechaIngreso, Date fechaModifica, Set certificacions) {
       this.codigoNoApto = codigoNoApto;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.estado = estado;
       this.nombreMotivo = nombreMotivo;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
       this.certificacions = certificacions;
    }
   
    public int getCodigoNoApto() {
        return this.codigoNoApto;
    }
    
    public void setCodigoNoApto(int codigoNoApto) {
        this.codigoNoApto = codigoNoApto;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombreMotivo() {
        return this.nombreMotivo;
    }
    
    public void setNombreMotivo(String nombreMotivo) {
        this.nombreMotivo = nombreMotivo;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }
    public Set getCertificacions() {
        return this.certificacions;
    }
    
    public void setCertificacions(Set certificacions) {
        this.certificacions = certificacions;
    }




}


