package Pojos;
// Generated Aug 21, 2024 1:22:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private String dpi;
     private DepartamentoResidencia departamentoResidencia;
     private Grado grado;
     private Poblacion poblacion;
     private Usuario usuarioByUsuarioIngreso;
     private Usuario usuarioByUsuarioModifica;
     private Boolean estado;
     private String nombreCompleto;
     private String telefono;
     private Date fechaIngreso;
     private Date fechaModifica;
     private Set examens = new HashSet(0);

    public Persona() {
    }

	
    public Persona(String dpi) {
        this.dpi = dpi;
    }
    public Persona(String dpi, DepartamentoResidencia departamentoResidencia, Grado grado, Poblacion poblacion, Usuario usuarioByUsuarioIngreso, Usuario usuarioByUsuarioModifica, Boolean estado, String nombreCompleto, String telefono, Date fechaIngreso, Date fechaModifica, Set examens) {
       this.dpi = dpi;
       this.departamentoResidencia = departamentoResidencia;
       this.grado = grado;
       this.poblacion = poblacion;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.estado = estado;
       this.nombreCompleto = nombreCompleto;
       this.telefono = telefono;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
       this.examens = examens;
    }
   
    public String getDpi() {
        return this.dpi;
    }
    
    public void setDpi(String dpi) {
        this.dpi = dpi;
    }
    public DepartamentoResidencia getDepartamentoResidencia() {
        return this.departamentoResidencia;
    }
    
    public void setDepartamentoResidencia(DepartamentoResidencia departamentoResidencia) {
        this.departamentoResidencia = departamentoResidencia;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public Poblacion getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(Poblacion poblacion) {
        this.poblacion = poblacion;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }
    public Set getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set examens) {
        this.examens = examens;
    }




}


