package Pojos;
// Generated Sep 3, 2024 5:05:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Poblacion generated by hbm2java
 */
public class Poblacion  implements java.io.Serializable {


     private int codigoPoblacion;
     private Usuario usuarioByUsuarioIngreso;
     private Usuario usuarioByUsuarioModifica;
     private Boolean estado;
     private String nombrePoblacion;
     private Date fechaIngreso;
     private Date fechaModifica;
     private Set personas = new HashSet(0);

    public Poblacion() {
    }

	
    public Poblacion(int codigoPoblacion) {
        this.codigoPoblacion = codigoPoblacion;
    }
    public Poblacion(int codigoPoblacion, Usuario usuarioByUsuarioIngreso, Usuario usuarioByUsuarioModifica, Boolean estado, String nombrePoblacion, Date fechaIngreso, Date fechaModifica, Set personas) {
       this.codigoPoblacion = codigoPoblacion;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.estado = estado;
       this.nombrePoblacion = nombrePoblacion;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
       this.personas = personas;
    }
   
    public int getCodigoPoblacion() {
        return this.codigoPoblacion;
    }
    
    public void setCodigoPoblacion(int codigoPoblacion) {
        this.codigoPoblacion = codigoPoblacion;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombrePoblacion() {
        return this.nombrePoblacion;
    }
    
    public void setNombrePoblacion(String nombrePoblacion) {
        this.nombrePoblacion = nombrePoblacion;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


