package Pojos;
// Generated Oct 24, 2024 12:41:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Poblacion generated by hbm2java
 */
public class Poblacion  implements java.io.Serializable {


     private Integer codigoPoblacion;
     private Boolean estado;
     private String nombrePoblacion;
     private Set usuarios = new HashSet(0);

    public Poblacion() {
    }

    public Poblacion(Boolean estado, String nombrePoblacion, Set usuarios) {
       this.estado = estado;
       this.nombrePoblacion = nombrePoblacion;
       this.usuarios = usuarios;
    }
   
    public Integer getCodigoPoblacion() {
        return this.codigoPoblacion;
    }
    
    public void setCodigoPoblacion(Integer codigoPoblacion) {
        this.codigoPoblacion = codigoPoblacion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombrePoblacion() {
        return this.nombrePoblacion;
    }
    
    public void setNombrePoblacion(String nombrePoblacion) {
        this.nombrePoblacion = nombrePoblacion;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


