package Pojos;
// Generated Oct 23, 2024 11:02:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private int codigoPregunta;
     private Usuario usuarioByUsuarioIngreso;
     private Usuario usuarioByUsuarioModifica;
     private Boolean estado;
     private String enunciado;
     private BigDecimal punteo;
     private Date fechaIngreso;
     private Date fechaModifica;
     private Set detalles = new HashSet(0);
     private Set respuestas = new HashSet(0);

    public Pregunta() {
    }

	
    public Pregunta(int codigoPregunta) {
        this.codigoPregunta = codigoPregunta;
    }
    public Pregunta(int codigoPregunta, Usuario usuarioByUsuarioIngreso, Usuario usuarioByUsuarioModifica, Boolean estado, String enunciado, BigDecimal punteo, Date fechaIngreso, Date fechaModifica, Set detalles, Set respuestas) {
       this.codigoPregunta = codigoPregunta;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.estado = estado;
       this.enunciado = enunciado;
       this.punteo = punteo;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
       this.detalles = detalles;
       this.respuestas = respuestas;
    }
   
    public int getCodigoPregunta() {
        return this.codigoPregunta;
    }
    
    public void setCodigoPregunta(int codigoPregunta) {
        this.codigoPregunta = codigoPregunta;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getEnunciado() {
        return this.enunciado;
    }
    
    public void setEnunciado(String enunciado) {
        this.enunciado = enunciado;
    }
    public BigDecimal getPunteo() {
        return this.punteo;
    }
    
    public void setPunteo(BigDecimal punteo) {
        this.punteo = punteo;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }
    public Set getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }




}


