package Pojos;
// Generated Aug 21, 2024 1:22:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private int codigoRespuesta;
     private BancoRespuestas bancoRespuestas;
     private Usuario usuarioByUsuarioModifica;
     private Usuario usuarioByUsuarioIngreso;
     private Boolean estado;
     private String enunciado;
     private Date fechaIngreso;
     private Date fechaModifica;
     private Set detalleExamens = new HashSet(0);

    public Pregunta() {
    }

	
    public Pregunta(int codigoRespuesta) {
        this.codigoRespuesta = codigoRespuesta;
    }
    public Pregunta(int codigoRespuesta, BancoRespuestas bancoRespuestas, Usuario usuarioByUsuarioModifica, Usuario usuarioByUsuarioIngreso, Boolean estado, String enunciado, Date fechaIngreso, Date fechaModifica, Set detalleExamens) {
       this.codigoRespuesta = codigoRespuesta;
       this.bancoRespuestas = bancoRespuestas;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.estado = estado;
       this.enunciado = enunciado;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
       this.detalleExamens = detalleExamens;
    }
   
    public int getCodigoRespuesta() {
        return this.codigoRespuesta;
    }
    
    public void setCodigoRespuesta(int codigoRespuesta) {
        this.codigoRespuesta = codigoRespuesta;
    }
    public BancoRespuestas getBancoRespuestas() {
        return this.bancoRespuestas;
    }
    
    public void setBancoRespuestas(BancoRespuestas bancoRespuestas) {
        this.bancoRespuestas = bancoRespuestas;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getEnunciado() {
        return this.enunciado;
    }
    
    public void setEnunciado(String enunciado) {
        this.enunciado = enunciado;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }
    public Set getDetalleExamens() {
        return this.detalleExamens;
    }
    
    public void setDetalleExamens(Set detalleExamens) {
        this.detalleExamens = detalleExamens;
    }




}


