package Pojos;
// Generated Oct 24, 2024 12:41:15 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Respuesta generated by hbm2java
 */
public class Respuesta  implements java.io.Serializable {


     private Integer codigoRespuesta;
     private Pregunta pregunta;
     private Usuario usuarioByUsuarioModifica;
     private Usuario usuarioByUsuarioIngreso;
     private Boolean estado;
     private String respuesta;
     private Boolean escorrecta;
     private Date fechaIngreso;
     private Date fechaModifica;

    public Respuesta() {
    }

    public Respuesta(Pregunta pregunta, Usuario usuarioByUsuarioModifica, Usuario usuarioByUsuarioIngreso, Boolean estado, String respuesta, Boolean escorrecta, Date fechaIngreso, Date fechaModifica) {
       this.pregunta = pregunta;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.estado = estado;
       this.respuesta = respuesta;
       this.escorrecta = escorrecta;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
    }
   
    public Integer getCodigoRespuesta() {
        return this.codigoRespuesta;
    }
    
    public void setCodigoRespuesta(Integer codigoRespuesta) {
        this.codigoRespuesta = codigoRespuesta;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public Boolean getEscorrecta() {
        return this.escorrecta;
    }
    
    public void setEscorrecta(Boolean escorrecta) {
        this.escorrecta = escorrecta;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }




}


