package Pojos;
// Generated Sep 3, 2024 5:05:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int codigoUsuario;
     private Boolean estado;
     private String nombreUsuario;
     private String rol;
     private String contrasenia;
     private Set preguntasForUsuarioModifica = new HashSet(0);
     private Set certificacionsForUsarioIngresa = new HashSet(0);
     private Set gradosForUsuarioIngreso = new HashSet(0);
     private Set certificacionsForUsuarioModifica = new HashSet(0);
     private Set poblacionsForUsuarioIngreso = new HashSet(0);
     private Set gradosForUsuarioModifica = new HashSet(0);
     private Set bancoRespuestasesForUsuarioModifica = new HashSet(0);
     private Set motivoEvaluacionsForUsuarioModifica = new HashSet(0);
     private Set motivoNoAptosForUsuarioIngreso = new HashSet(0);
     private Set departamentoResidenciasForUsuarioIngreso = new HashSet(0);
     private Set bancoRespuestasesForUsuarioIngreso = new HashSet(0);
     private Set detalleExamensForUsuarioIngreso = new HashSet(0);
     private Set motivoEvaluacionsForUsuarioIngreso = new HashSet(0);
     private Set detalleExamensForUsuarioModifica = new HashSet(0);
     private Set personasForUsuarioIngreso = new HashSet(0);
     private Set poblacionsForUsuarioModifica = new HashSet(0);
     private Set personasForUsuarioModifica = new HashSet(0);
     private Set departamentoResidenciasForUsuarioModifica = new HashSet(0);
     private Set empleosForUsuarioModifica = new HashSet(0);
     private Set empleosForUsuarioIngreso = new HashSet(0);
     private Set preguntasForUsuarioIngreso = new HashSet(0);
     private Set comandosForUsuarioIngreso = new HashSet(0);
     private Set examensForUsuarioIngreso = new HashSet(0);
     private Set motivoNoAptosForUsuarioModifica = new HashSet(0);
     private Set comandosForUsuarioModifica = new HashSet(0);
     private Set examensForUsuarioModifica = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int codigoUsuario) {
        this.codigoUsuario = codigoUsuario;
    }
    public Usuario(int codigoUsuario, Boolean estado, String nombreUsuario, String rol, String contrasenia, Set preguntasForUsuarioModifica, Set certificacionsForUsarioIngresa, Set gradosForUsuarioIngreso, Set certificacionsForUsuarioModifica, Set poblacionsForUsuarioIngreso, Set gradosForUsuarioModifica, Set bancoRespuestasesForUsuarioModifica, Set motivoEvaluacionsForUsuarioModifica, Set motivoNoAptosForUsuarioIngreso, Set departamentoResidenciasForUsuarioIngreso, Set bancoRespuestasesForUsuarioIngreso, Set detalleExamensForUsuarioIngreso, Set motivoEvaluacionsForUsuarioIngreso, Set detalleExamensForUsuarioModifica, Set personasForUsuarioIngreso, Set poblacionsForUsuarioModifica, Set personasForUsuarioModifica, Set departamentoResidenciasForUsuarioModifica, Set empleosForUsuarioModifica, Set empleosForUsuarioIngreso, Set preguntasForUsuarioIngreso, Set comandosForUsuarioIngreso, Set examensForUsuarioIngreso, Set motivoNoAptosForUsuarioModifica, Set comandosForUsuarioModifica, Set examensForUsuarioModifica) {
       this.codigoUsuario = codigoUsuario;
       this.estado = estado;
       this.nombreUsuario = nombreUsuario;
       this.rol = rol;
       this.contrasenia = contrasenia;
       this.preguntasForUsuarioModifica = preguntasForUsuarioModifica;
       this.certificacionsForUsarioIngresa = certificacionsForUsarioIngresa;
       this.gradosForUsuarioIngreso = gradosForUsuarioIngreso;
       this.certificacionsForUsuarioModifica = certificacionsForUsuarioModifica;
       this.poblacionsForUsuarioIngreso = poblacionsForUsuarioIngreso;
       this.gradosForUsuarioModifica = gradosForUsuarioModifica;
       this.bancoRespuestasesForUsuarioModifica = bancoRespuestasesForUsuarioModifica;
       this.motivoEvaluacionsForUsuarioModifica = motivoEvaluacionsForUsuarioModifica;
       this.motivoNoAptosForUsuarioIngreso = motivoNoAptosForUsuarioIngreso;
       this.departamentoResidenciasForUsuarioIngreso = departamentoResidenciasForUsuarioIngreso;
       this.bancoRespuestasesForUsuarioIngreso = bancoRespuestasesForUsuarioIngreso;
       this.detalleExamensForUsuarioIngreso = detalleExamensForUsuarioIngreso;
       this.motivoEvaluacionsForUsuarioIngreso = motivoEvaluacionsForUsuarioIngreso;
       this.detalleExamensForUsuarioModifica = detalleExamensForUsuarioModifica;
       this.personasForUsuarioIngreso = personasForUsuarioIngreso;
       this.poblacionsForUsuarioModifica = poblacionsForUsuarioModifica;
       this.personasForUsuarioModifica = personasForUsuarioModifica;
       this.departamentoResidenciasForUsuarioModifica = departamentoResidenciasForUsuarioModifica;
       this.empleosForUsuarioModifica = empleosForUsuarioModifica;
       this.empleosForUsuarioIngreso = empleosForUsuarioIngreso;
       this.preguntasForUsuarioIngreso = preguntasForUsuarioIngreso;
       this.comandosForUsuarioIngreso = comandosForUsuarioIngreso;
       this.examensForUsuarioIngreso = examensForUsuarioIngreso;
       this.motivoNoAptosForUsuarioModifica = motivoNoAptosForUsuarioModifica;
       this.comandosForUsuarioModifica = comandosForUsuarioModifica;
       this.examensForUsuarioModifica = examensForUsuarioModifica;
    }
   
    public int getCodigoUsuario() {
        return this.codigoUsuario;
    }
    
    public void setCodigoUsuario(int codigoUsuario) {
        this.codigoUsuario = codigoUsuario;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Set getPreguntasForUsuarioModifica() {
        return this.preguntasForUsuarioModifica;
    }
    
    public void setPreguntasForUsuarioModifica(Set preguntasForUsuarioModifica) {
        this.preguntasForUsuarioModifica = preguntasForUsuarioModifica;
    }
    public Set getCertificacionsForUsarioIngresa() {
        return this.certificacionsForUsarioIngresa;
    }
    
    public void setCertificacionsForUsarioIngresa(Set certificacionsForUsarioIngresa) {
        this.certificacionsForUsarioIngresa = certificacionsForUsarioIngresa;
    }
    public Set getGradosForUsuarioIngreso() {
        return this.gradosForUsuarioIngreso;
    }
    
    public void setGradosForUsuarioIngreso(Set gradosForUsuarioIngreso) {
        this.gradosForUsuarioIngreso = gradosForUsuarioIngreso;
    }
    public Set getCertificacionsForUsuarioModifica() {
        return this.certificacionsForUsuarioModifica;
    }
    
    public void setCertificacionsForUsuarioModifica(Set certificacionsForUsuarioModifica) {
        this.certificacionsForUsuarioModifica = certificacionsForUsuarioModifica;
    }
    public Set getPoblacionsForUsuarioIngreso() {
        return this.poblacionsForUsuarioIngreso;
    }
    
    public void setPoblacionsForUsuarioIngreso(Set poblacionsForUsuarioIngreso) {
        this.poblacionsForUsuarioIngreso = poblacionsForUsuarioIngreso;
    }
    public Set getGradosForUsuarioModifica() {
        return this.gradosForUsuarioModifica;
    }
    
    public void setGradosForUsuarioModifica(Set gradosForUsuarioModifica) {
        this.gradosForUsuarioModifica = gradosForUsuarioModifica;
    }
    public Set getBancoRespuestasesForUsuarioModifica() {
        return this.bancoRespuestasesForUsuarioModifica;
    }
    
    public void setBancoRespuestasesForUsuarioModifica(Set bancoRespuestasesForUsuarioModifica) {
        this.bancoRespuestasesForUsuarioModifica = bancoRespuestasesForUsuarioModifica;
    }
    public Set getMotivoEvaluacionsForUsuarioModifica() {
        return this.motivoEvaluacionsForUsuarioModifica;
    }
    
    public void setMotivoEvaluacionsForUsuarioModifica(Set motivoEvaluacionsForUsuarioModifica) {
        this.motivoEvaluacionsForUsuarioModifica = motivoEvaluacionsForUsuarioModifica;
    }
    public Set getMotivoNoAptosForUsuarioIngreso() {
        return this.motivoNoAptosForUsuarioIngreso;
    }
    
    public void setMotivoNoAptosForUsuarioIngreso(Set motivoNoAptosForUsuarioIngreso) {
        this.motivoNoAptosForUsuarioIngreso = motivoNoAptosForUsuarioIngreso;
    }
    public Set getDepartamentoResidenciasForUsuarioIngreso() {
        return this.departamentoResidenciasForUsuarioIngreso;
    }
    
    public void setDepartamentoResidenciasForUsuarioIngreso(Set departamentoResidenciasForUsuarioIngreso) {
        this.departamentoResidenciasForUsuarioIngreso = departamentoResidenciasForUsuarioIngreso;
    }
    public Set getBancoRespuestasesForUsuarioIngreso() {
        return this.bancoRespuestasesForUsuarioIngreso;
    }
    
    public void setBancoRespuestasesForUsuarioIngreso(Set bancoRespuestasesForUsuarioIngreso) {
        this.bancoRespuestasesForUsuarioIngreso = bancoRespuestasesForUsuarioIngreso;
    }
    public Set getDetalleExamensForUsuarioIngreso() {
        return this.detalleExamensForUsuarioIngreso;
    }
    
    public void setDetalleExamensForUsuarioIngreso(Set detalleExamensForUsuarioIngreso) {
        this.detalleExamensForUsuarioIngreso = detalleExamensForUsuarioIngreso;
    }
    public Set getMotivoEvaluacionsForUsuarioIngreso() {
        return this.motivoEvaluacionsForUsuarioIngreso;
    }
    
    public void setMotivoEvaluacionsForUsuarioIngreso(Set motivoEvaluacionsForUsuarioIngreso) {
        this.motivoEvaluacionsForUsuarioIngreso = motivoEvaluacionsForUsuarioIngreso;
    }
    public Set getDetalleExamensForUsuarioModifica() {
        return this.detalleExamensForUsuarioModifica;
    }
    
    public void setDetalleExamensForUsuarioModifica(Set detalleExamensForUsuarioModifica) {
        this.detalleExamensForUsuarioModifica = detalleExamensForUsuarioModifica;
    }
    public Set getPersonasForUsuarioIngreso() {
        return this.personasForUsuarioIngreso;
    }
    
    public void setPersonasForUsuarioIngreso(Set personasForUsuarioIngreso) {
        this.personasForUsuarioIngreso = personasForUsuarioIngreso;
    }
    public Set getPoblacionsForUsuarioModifica() {
        return this.poblacionsForUsuarioModifica;
    }
    
    public void setPoblacionsForUsuarioModifica(Set poblacionsForUsuarioModifica) {
        this.poblacionsForUsuarioModifica = poblacionsForUsuarioModifica;
    }
    public Set getPersonasForUsuarioModifica() {
        return this.personasForUsuarioModifica;
    }
    
    public void setPersonasForUsuarioModifica(Set personasForUsuarioModifica) {
        this.personasForUsuarioModifica = personasForUsuarioModifica;
    }
    public Set getDepartamentoResidenciasForUsuarioModifica() {
        return this.departamentoResidenciasForUsuarioModifica;
    }
    
    public void setDepartamentoResidenciasForUsuarioModifica(Set departamentoResidenciasForUsuarioModifica) {
        this.departamentoResidenciasForUsuarioModifica = departamentoResidenciasForUsuarioModifica;
    }
    public Set getEmpleosForUsuarioModifica() {
        return this.empleosForUsuarioModifica;
    }
    
    public void setEmpleosForUsuarioModifica(Set empleosForUsuarioModifica) {
        this.empleosForUsuarioModifica = empleosForUsuarioModifica;
    }
    public Set getEmpleosForUsuarioIngreso() {
        return this.empleosForUsuarioIngreso;
    }
    
    public void setEmpleosForUsuarioIngreso(Set empleosForUsuarioIngreso) {
        this.empleosForUsuarioIngreso = empleosForUsuarioIngreso;
    }
    public Set getPreguntasForUsuarioIngreso() {
        return this.preguntasForUsuarioIngreso;
    }
    
    public void setPreguntasForUsuarioIngreso(Set preguntasForUsuarioIngreso) {
        this.preguntasForUsuarioIngreso = preguntasForUsuarioIngreso;
    }
    public Set getComandosForUsuarioIngreso() {
        return this.comandosForUsuarioIngreso;
    }
    
    public void setComandosForUsuarioIngreso(Set comandosForUsuarioIngreso) {
        this.comandosForUsuarioIngreso = comandosForUsuarioIngreso;
    }
    public Set getExamensForUsuarioIngreso() {
        return this.examensForUsuarioIngreso;
    }
    
    public void setExamensForUsuarioIngreso(Set examensForUsuarioIngreso) {
        this.examensForUsuarioIngreso = examensForUsuarioIngreso;
    }
    public Set getMotivoNoAptosForUsuarioModifica() {
        return this.motivoNoAptosForUsuarioModifica;
    }
    
    public void setMotivoNoAptosForUsuarioModifica(Set motivoNoAptosForUsuarioModifica) {
        this.motivoNoAptosForUsuarioModifica = motivoNoAptosForUsuarioModifica;
    }
    public Set getComandosForUsuarioModifica() {
        return this.comandosForUsuarioModifica;
    }
    
    public void setComandosForUsuarioModifica(Set comandosForUsuarioModifica) {
        this.comandosForUsuarioModifica = comandosForUsuarioModifica;
    }
    public Set getExamensForUsuarioModifica() {
        return this.examensForUsuarioModifica;
    }
    
    public void setExamensForUsuarioModifica(Set examensForUsuarioModifica) {
        this.examensForUsuarioModifica = examensForUsuarioModifica;
    }




}


