package Pojos;
// Generated Oct 24, 2024 12:41:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String dpi;
     private Comando comando;
     private DepartamentoResidencia departamentoResidencia;
     private Grado grado;
     private Poblacion poblacion;
     private Boolean estado;
     private String nombreCompleto;
     private String telefono;
     private String nombreUsuario;
     private String rol;
     private String contrasenia;
     private Set asignacionsForUsuarioIngreso = new HashSet(0);
     private Set detallesForUsuarioIngreso = new HashSet(0);
     private Set asignacionsForUsuarioModifica = new HashSet(0);
     private Set detallesForUsuarioModifica = new HashSet(0);
     private Set preguntasForUsuarioModifica = new HashSet(0);
     private Set empleosForUsuarioModifica = new HashSet(0);
     private Set asignacionsForEvaluado = new HashSet(0);
     private Set empleosForUsuarioIngreso = new HashSet(0);
     private Set preguntasForUsuarioIngreso = new HashSet(0);
     private Set respuestasForUsuarioModifica = new HashSet(0);
     private Set examensForUsuarioIngreso = new HashSet(0);
     private Set respuestasForUsuarioIngreso = new HashSet(0);
     private Set examensForUsuarioModifica = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String dpi) {
        this.dpi = dpi;
    }
    public Usuario(String dpi, Comando comando, DepartamentoResidencia departamentoResidencia, Grado grado, Poblacion poblacion, Boolean estado, String nombreCompleto, String telefono, String nombreUsuario, String rol, String contrasenia, Set asignacionsForUsuarioIngreso, Set detallesForUsuarioIngreso, Set asignacionsForUsuarioModifica, Set detallesForUsuarioModifica, Set preguntasForUsuarioModifica, Set empleosForUsuarioModifica, Set asignacionsForEvaluado, Set empleosForUsuarioIngreso, Set preguntasForUsuarioIngreso, Set respuestasForUsuarioModifica, Set examensForUsuarioIngreso, Set respuestasForUsuarioIngreso, Set examensForUsuarioModifica) {
       this.dpi = dpi;
       this.comando = comando;
       this.departamentoResidencia = departamentoResidencia;
       this.grado = grado;
       this.poblacion = poblacion;
       this.estado = estado;
       this.nombreCompleto = nombreCompleto;
       this.telefono = telefono;
       this.nombreUsuario = nombreUsuario;
       this.rol = rol;
       this.contrasenia = contrasenia;
       this.asignacionsForUsuarioIngreso = asignacionsForUsuarioIngreso;
       this.detallesForUsuarioIngreso = detallesForUsuarioIngreso;
       this.asignacionsForUsuarioModifica = asignacionsForUsuarioModifica;
       this.detallesForUsuarioModifica = detallesForUsuarioModifica;
       this.preguntasForUsuarioModifica = preguntasForUsuarioModifica;
       this.empleosForUsuarioModifica = empleosForUsuarioModifica;
       this.asignacionsForEvaluado = asignacionsForEvaluado;
       this.empleosForUsuarioIngreso = empleosForUsuarioIngreso;
       this.preguntasForUsuarioIngreso = preguntasForUsuarioIngreso;
       this.respuestasForUsuarioModifica = respuestasForUsuarioModifica;
       this.examensForUsuarioIngreso = examensForUsuarioIngreso;
       this.respuestasForUsuarioIngreso = respuestasForUsuarioIngreso;
       this.examensForUsuarioModifica = examensForUsuarioModifica;
    }
   
    public String getDpi() {
        return this.dpi;
    }
    
    public void setDpi(String dpi) {
        this.dpi = dpi;
    }
    public Comando getComando() {
        return this.comando;
    }
    
    public void setComando(Comando comando) {
        this.comando = comando;
    }
    public DepartamentoResidencia getDepartamentoResidencia() {
        return this.departamentoResidencia;
    }
    
    public void setDepartamentoResidencia(DepartamentoResidencia departamentoResidencia) {
        this.departamentoResidencia = departamentoResidencia;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public Poblacion getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(Poblacion poblacion) {
        this.poblacion = poblacion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Set getAsignacionsForUsuarioIngreso() {
        return this.asignacionsForUsuarioIngreso;
    }
    
    public void setAsignacionsForUsuarioIngreso(Set asignacionsForUsuarioIngreso) {
        this.asignacionsForUsuarioIngreso = asignacionsForUsuarioIngreso;
    }
    public Set getDetallesForUsuarioIngreso() {
        return this.detallesForUsuarioIngreso;
    }
    
    public void setDetallesForUsuarioIngreso(Set detallesForUsuarioIngreso) {
        this.detallesForUsuarioIngreso = detallesForUsuarioIngreso;
    }
    public Set getAsignacionsForUsuarioModifica() {
        return this.asignacionsForUsuarioModifica;
    }
    
    public void setAsignacionsForUsuarioModifica(Set asignacionsForUsuarioModifica) {
        this.asignacionsForUsuarioModifica = asignacionsForUsuarioModifica;
    }
    public Set getDetallesForUsuarioModifica() {
        return this.detallesForUsuarioModifica;
    }
    
    public void setDetallesForUsuarioModifica(Set detallesForUsuarioModifica) {
        this.detallesForUsuarioModifica = detallesForUsuarioModifica;
    }
    public Set getPreguntasForUsuarioModifica() {
        return this.preguntasForUsuarioModifica;
    }
    
    public void setPreguntasForUsuarioModifica(Set preguntasForUsuarioModifica) {
        this.preguntasForUsuarioModifica = preguntasForUsuarioModifica;
    }
    public Set getEmpleosForUsuarioModifica() {
        return this.empleosForUsuarioModifica;
    }
    
    public void setEmpleosForUsuarioModifica(Set empleosForUsuarioModifica) {
        this.empleosForUsuarioModifica = empleosForUsuarioModifica;
    }
    public Set getAsignacionsForEvaluado() {
        return this.asignacionsForEvaluado;
    }
    
    public void setAsignacionsForEvaluado(Set asignacionsForEvaluado) {
        this.asignacionsForEvaluado = asignacionsForEvaluado;
    }
    public Set getEmpleosForUsuarioIngreso() {
        return this.empleosForUsuarioIngreso;
    }
    
    public void setEmpleosForUsuarioIngreso(Set empleosForUsuarioIngreso) {
        this.empleosForUsuarioIngreso = empleosForUsuarioIngreso;
    }
    public Set getPreguntasForUsuarioIngreso() {
        return this.preguntasForUsuarioIngreso;
    }
    
    public void setPreguntasForUsuarioIngreso(Set preguntasForUsuarioIngreso) {
        this.preguntasForUsuarioIngreso = preguntasForUsuarioIngreso;
    }
    public Set getRespuestasForUsuarioModifica() {
        return this.respuestasForUsuarioModifica;
    }
    
    public void setRespuestasForUsuarioModifica(Set respuestasForUsuarioModifica) {
        this.respuestasForUsuarioModifica = respuestasForUsuarioModifica;
    }
    public Set getExamensForUsuarioIngreso() {
        return this.examensForUsuarioIngreso;
    }
    
    public void setExamensForUsuarioIngreso(Set examensForUsuarioIngreso) {
        this.examensForUsuarioIngreso = examensForUsuarioIngreso;
    }
    public Set getRespuestasForUsuarioIngreso() {
        return this.respuestasForUsuarioIngreso;
    }
    
    public void setRespuestasForUsuarioIngreso(Set respuestasForUsuarioIngreso) {
        this.respuestasForUsuarioIngreso = respuestasForUsuarioIngreso;
    }
    public Set getExamensForUsuarioModifica() {
        return this.examensForUsuarioModifica;
    }
    
    public void setExamensForUsuarioModifica(Set examensForUsuarioModifica) {
        this.examensForUsuarioModifica = examensForUsuarioModifica;
    }




}


