package Pojos;
// Generated Aug 21, 2024 1:22:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BancoRespuestas generated by hbm2java
 */
public class BancoRespuestas  implements java.io.Serializable {


     private int codigoPregunta;
     private Usuario usuarioByUsuarioModifica;
     private Usuario usuarioByUsuarioIngreso;
     private Boolean estado;
     private String respuesta;
     private Date fechaIngreso;
     private Date fechaModifica;
     private Set preguntas = new HashSet(0);

    public BancoRespuestas() {
    }

	
    public BancoRespuestas(int codigoPregunta) {
        this.codigoPregunta = codigoPregunta;
    }
    public BancoRespuestas(int codigoPregunta, Usuario usuarioByUsuarioModifica, Usuario usuarioByUsuarioIngreso, Boolean estado, String respuesta, Date fechaIngreso, Date fechaModifica, Set preguntas) {
       this.codigoPregunta = codigoPregunta;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.estado = estado;
       this.respuesta = respuesta;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
       this.preguntas = preguntas;
    }
   
    public int getCodigoPregunta() {
        return this.codigoPregunta;
    }
    
    public void setCodigoPregunta(int codigoPregunta) {
        this.codigoPregunta = codigoPregunta;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }




}


