package Pojos;
// Generated Aug 21, 2024 1:22:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Grado generated by hbm2java
 */
public class Grado  implements java.io.Serializable {


     private int codigoGrado;
     private Usuario usuarioByUsuarioIngreso;
     private Usuario usuarioByUsuarioModifica;
     private Boolean estado;
     private String nombreGrado;
     private Date fechaIngreso;
     private Date fechaModifica;
     private Set personas = new HashSet(0);

    public Grado() {
    }

	
    public Grado(int codigoGrado) {
        this.codigoGrado = codigoGrado;
    }
    public Grado(int codigoGrado, Usuario usuarioByUsuarioIngreso, Usuario usuarioByUsuarioModifica, Boolean estado, String nombreGrado, Date fechaIngreso, Date fechaModifica, Set personas) {
       this.codigoGrado = codigoGrado;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.estado = estado;
       this.nombreGrado = nombreGrado;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
       this.personas = personas;
    }
   
    public int getCodigoGrado() {
        return this.codigoGrado;
    }
    
    public void setCodigoGrado(int codigoGrado) {
        this.codigoGrado = codigoGrado;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombreGrado() {
        return this.nombreGrado;
    }
    
    public void setNombreGrado(String nombreGrado) {
        this.nombreGrado = nombreGrado;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


